const themes = [
  'agate',
  'androidstudio',
  'arduino-light',
  'arta',
  'ascetic',
  'atelier-cave-dark',
  'atelier-cave-light',
  'atelier-dune-dark',
  'atelier-dune-light',
  'atelier-estuary-dark',
  'atelier-estuary-light',
  'atelier-forest-dark',
  'atelier-forest-light',
  'atelier-heath-dark',
  'atelier-heath-light',
  'atelier-lakeside-dark',
  'atelier-lakeside-light',
  'atelier-plateau-dark',
  'atelier-plateau-light',
  'atelier-savanna-dark',
  'atelier-savanna-light',
  'atelier-seaside-dark',
  'atelier-seaside-light',
  'atelier-sulphurpool-dark',
  'atelier-sulphurpool-light',
  'atom-one-dark',
  'atom-one-light',
  'codepen-embed',
  'color-brewer',
  'darcula',
  'dark',
  'default',
  'docco',
  'dracula',
  'far',
  'foundation',
  'github',
  'github-gist',
  'googlecode',
  'grayscale',
  'gruvbox-dark',
  'gruvbox-light',
  'hopscotch',
  'hybrid',
  'idea',
  'ir-black',
  'kimbie.dark',
  'kimbie.light',
  'magula',
  'mono-blue',
  'monokai',
  'monokai-sublime',
  'obsidian',
  'ocean',
  'paraiso-dark',
  'paraiso-light',
  'purebasic',
  'qtcreator_dark',
  'qtcreator_light',
  'railscasts',
  'rainbow',
  'solarized-dark',
  'solarized-light',
  'sunburst',
  'tomorrow',
  'tomorrow-night-blue',
  'tomorrow-night-bright',
  'tomorrow-night',
  'tomorrow-night-eighties',
  'vs',
  'xcode',
  'xt256',
  'zenburn',
];

// themes.forEach(function(value) {
//   console.log(`
// .${value} {
//   @import "~highlight.js/styles/${value}";
//   @include common;
// }`);
// })

exports = module.exports = themes;